services:
  postgres:
    container_name: unnos-pg
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - unnos-pg:/data/postgres

volumes:
  unnos-pg: