services:
  web:
    container_name: unnos-web
    build:
      context: .
      dockerfile: ./web/.nixpacks/Dockerfile
      args:
        - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    image: unnos-web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    networks:
      - default

  bot:
    container_name: unnos-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: unnos-bot
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    networks:
      - default

  postgres:
    container_name: unnos-pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - unnos-pg:/data/postgres
    networks:
      - default

volumes:
  unnos-pg:

networks:
  default:
